### ISSUE TITLE
Funding storage and events uses user controlled amount rather than actual amount

### ISSUE THREAD

**Issue by DanielVF** [gysr-io/core#1]
In the fund() function of C20BaseRewardModule, the code carefully checks the actual amount transferred in to handle tokens that do not transfer the requested amount. However, this actual amount is then ignored later in the method and the user controlled value is used when creating the stored funding struct, and when emitting an event.

```javascript
    // https://github.com/gysr-io/core/blob/73278bea761c7d799bd890da66ebc737c49ed912/contracts/ERC20BaseRewardModule.sol
    // in function _fund(...)
    ...
    // do transfer of funding
    uint256 total = rewardToken.balanceOf(address(this));
    rewardToken.safeTransferFrom(msg.sender, address(this), amount); 
    uint256 actual = rewardToken.balanceOf(address(this)) - total; // <--- A 

    // mint shares at current rate
    uint256 minted =
        (total > 0)
            ? (_shares[token] * actual) / total
            : actual * INITIAL_SHARES_PER_TOKEN;

    _locked[token] += minted;
    _shares[token] += minted;

    // create new funding
    _fundings[token].push(
        Funding({
            amount: amount, // <--- B
            shares: minted,
            locked: minted,
            updated: start,
            start: start,
            duration: duration
        })
    );

    emit RewardsFunded(token, amount, minted, start); // <--- C
```    

I don't see an immediate impact from this, the funding amount storage in the struct is not used later in the contracts.

This could cause external systems that depend on these events/storage to act incorrectly, or could cause a cause a problem in a future revision of the contract, if these values were trusted by later code.

Feels like it would be better to only store and emit actual amounts, rather than user controlled amounts.

**Comment by DanielVF** [comment]
There's a similar situation in https://github.com/gysr-io/core/blob/73278bea761c7d799bd890da66ebc737c49ed912/contracts/ERC20StakingModule.sol#L119

**Comment by devinaconley** [comment]
Hi @DanielVF , thanks for the report on this!

Across the core contracts, all internal accounting is done using the `shares` value associated with the position or funding. This allows us to support rebasing tokens, interest bearing tokens, transfer fee tokens, etc. The case you call out, where requested transfer amount differs from the actual transfer amount, would be very common with a transfer fee token.

Here are a few examples of handling transfer fee tokens from the tests:
https://github.com/gysr-io/core/blob/55a918704c333a9d379433c07f5c1c5ffede8cb6/test/unit/erc20baserewardmodule.js#L1065
https://github.com/gysr-io/core/blob/55a918704c333a9d379433c07f5c1c5ffede8cb6/test/unit/erc20stakingmodule.js#L1012


Now on the decision to store/emit the requested amount, that's a great question. We thought about this one a lot, but ultimately decided on the convention for a few reasons:
- wanted the values to align with input data from external systems or users
- we could apply the convention universally (e.g. for unstakes/rewards, we'd have to do unnecessary computation to get the actual amounts, and for some internal bookkeeping it doesn't make sense)
- consistent with how events are emitted in other major protocols (e.g. uniswap)
- the actual amount is likely already emitted in the `Transfer` event
- it's generally consistent with our pattern of `amount`: aesthetic, `shares`: functional 

For some context, this approach was motivated by a compatibility issue between our V1 pool contract and the RFI token contract. Writeup here:
https://twitter.com/gysr_io/status/1334199474290368514

All that said, it's definitely an important detail for external systems to be aware of - will make sure to add it to the docs.

Thanks again!

**Comment by DanielVF** [comment]
Internal consistency good! Your thinking makes sense. Good luck with the protocol!
